@startuml
class com.pluralsight.accounting.Main {
~ {static} ArrayList<Transaction> ledger
~ {static} String csvFileName
+ {static} void main(String[])
- {static} void loadTransactions()
- {static} void makeDeposit()
- {static} void makePayment()
- {static} void Ledger()
+ {static} void viewAllTransactions()
~ {static} void saveTransactionToFile(Transaction)
+ {static} void showDeposits()
+ {static} void showPayments()
- {static} void reports()
+ {static} void monthToDate()
+ {static} void prevMonth()
+ {static} void yearToDate()
+ {static} void prevYear()
+ {static} void vendorSearch()
}


@enduml